# Generated by Django 5.0.14 on 2026-07-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquetipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Arquetipo",
                "verbose_name_plural": "Arquetipos",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "codigo_iso",
                    models.CharField(
                        help_text="Código ISO 3166-1 alpha-3", max_length=3, unique=True
                    ),
                ),
                (
                    "continente",
                    models.CharField(
                        choices=[
                            ("EU", "Europa"),
                            ("NA", "Norteamérica"),
                            ("LA", "América Latina"),
                            ("AS", "Asia"),
                            ("AF", "África"),
                            ("OC", "Oceanía"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
            },
        ),
        migrations.CreateModel(
            name="SerFolclorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion_breve",
                    models.TextField(help_text="Resumen de una línea"),
                ),
                ("descripcion_detallada", models.TextField(blank=True)),
                (
                    "arquetipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seres",
                        to="duermete_nino.arquetipo",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seres",
                        to="duermete_nino.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ser Folclórico",
                "verbose_name_plural": "Seres Folclóricos",
            },
        ),
    ]
