# Generated by Django 5.2.15 on 2026-07-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquetipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del arquetipo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Arquetipo",
                "verbose_name_plural": "Arquetipos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del país"),
                ),
                (
                    "codigo_iso",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Código ISO"
                    ),
                ),
                (
                    "continente",
                    models.CharField(
                        choices=[
                            ("AF", "África"),
                            ("AS", "Asia"),
                            ("EU", "Europa"),
                            ("NA", "Norteamérica"),
                            ("OC", "Oceanía"),
                            ("SA", "Sudamérica"),
                        ],
                        max_length=2,
                        verbose_name="Continente",
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SerFolclorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del ser"),
                ),
                (
                    "descripcion_breve",
                    models.TextField(max_length=300, verbose_name="Descripción breve"),
                ),
                (
                    "descripcion_detallada",
                    models.TextField(blank=True, verbose_name="Descripción detallada"),
                ),
                (
                    "arquetipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seres",
                        to="duermete_nino.arquetipo",
                        verbose_name="Arquetipo",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seres",
                        to="duermete_nino.pais",
                        verbose_name="País de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ser Folclórico",
                "verbose_name_plural": "Seres Folclóricos",
                "ordering": ["pais__nombre", "nombre"],
            },
        ),
    ]
