# Generated by Django 5.0.14 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duermete_nino", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arquetipo",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Arquetipo",
                "verbose_name_plural": "Arquetipos",
            },
        ),
        migrations.AlterModelOptions(
            name="pais",
            options={
                "ordering": ["nombre"],
                "verbose_name": "País",
                "verbose_name_plural": "Países",
            },
        ),
        migrations.AlterModelOptions(
            name="serfolclorico",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Ser Folclórico",
                "verbose_name_plural": "Seres Folclóricos",
            },
        ),
        migrations.AlterField(
            model_name="pais",
            name="nombre",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
